//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int QuestionNumber { get; set; }
        public System.Guid PersonId { get; set; }
        public System.DateTime AnswerTime { get; set; }
        public string AnswerText { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Question Question { get; set; }
    }
}
